export const HOST_PATTERNS: Record<string, string[]> = {
  opencode: ["opencode.ai"],
  "opencode-go": ["opencode.ai"],
  "opencode-zen": ["opencode.ai"],
  anthropic: ["api.anthropic.com", "console.anthropic.com"],
  openai: ["api.openai.com", "openai.azure.com"],
  "openai-codex": ["chatgpt.com", "api.openai.com"],
  azure: ["openai.azure.com"],
  google: [
    "generativelanguage.googleapis.com",
    "ai.google.dev",
    "cloudcode-pa.googleapis.com",
    "googleapis.com",
  ],
  "google-vertex": ["vertexai.googleapis.com", "aiplatform.googleapis.com"],
  "google-vertex-anthropic": ["vertexai.googleapis.com"],
  "github-copilot": [
    "api.githubcopilot.com",
    "copilot-proxy.githubusercontent.com",
    "githubcopilot.com",
  ],
  openrouter: ["openrouter.ai"],
  xai: ["api.x.ai"],
  groq: ["api.groq.com"],
  mistral: ["api.mistral.ai"],
  cohere: ["api.cohere.ai", "api.cohere.com"],
  together: ["api.together.xyz", "api.together.ai"],
  perplexity: ["api.perplexity.ai"],
  cerebras: ["api.cerebras.ai"],
  fireworks: ["api.fireworks.ai"],
  "amazon-bedrock": ["bedrock-runtime", "bedrock."],
  deepseek: ["api.deepseek.com"],
  moonshot: ["api.moonshot.cn"],
  kimi: ["api.moonshot.cn"],
  zhipu: ["open.bigmodel.cn", "api.z.ai"],
  alibaba: ["dashscope.aliyuncs.com"],
  qwen: ["dashscope.aliyuncs.com"],
  minimax: ["api.minimax.chat"],
  siliconflow: ["api.siliconflow.cn"],
}

export const DEFAULT_PROXIED_PROVIDERS = [
  "anthropic",
  "openai",
  "openai-codex",
  "google",
  "google-vertex",
  "google-vertex-anthropic",
  "github-copilot",
  "openrouter",
  "xai",
  "groq",
  "mistral",
  "cohere",
  "together",
  "perplexity",
  "cerebras",
  "fireworks",
  "amazon-bedrock",
]

export const DEFAULT_DIRECT_MODELS = [
  "glm-",
  "kimi-",
  "deepseek-",
  "qwen",
  "minimax-",
  "mimo-",
  "longcat",
  "hy3",
  "hy4",
]

export const DEFAULT_DIRECT_MODEL_HOSTS = ["opencode.ai"]
